local function getPhpVersion()
  local defaultVersion = '7.0.33'
  local root = vim.fs.root(0, 'php_version')
  if not root then
    return defaultVersion
  end
  return require('utils.files').read(root .. '/php_version')
end

return {
  cmd = { 'intelephense', '--stdio' },
  filetypes = { 'php' },
  root_markers = { 'vendor/', 'includes/' },
  commands = {
    IntelephenseIndex = {
      function()
        local clients = vim.lsp.get_clients({ name = 'intelephense' })
        clients[1]:exec_cmd({ title = 'php_index_workspace', command = 'intelephense.index.workspace' })
      end,
    },
  },
  before_init = function (_, config)
    config.settings.intelephense.environment = { phpVersion = getPhpVersion() }
  end,
  settings = {
    intelephense = {
      telemetry = { enabled = false },
      format = { enable = false },
      completion = {
        triggerParameterHints = true,
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = true,
      },
      files = {
        maxSize = 1000000,
        exclude = {
          '**/.git/**',
          '**/.svn/**',
          '**/.hg/**',
          '**/CVS/**',
          '**/.DS_Store/**',
          '**/node_modules/**',
          '**/bower_components/**',
          '**/vendor/**/{Test,test,Tests,tests}/**',
          '**/tests/**',
          '**/cache/**',
          '**/fpdf/**',
          '**/libs/**',
          '**/extras/**',
          '**/modalLoading-master/**',
          '**/node-modules/**',
          '**/nusoap-0.9.5/**',
          '**/PDFObject/**',
          '**/php-barcode-master/**',
          '**/PHPMailer/**',
          '**/php-qrcode-master/**',
          '**/trianglify-master/**',
        },
      },
      trace = { server = 'messages' },
      stubs = {
        'apache',
        'bcmath',
        'bz2',
        'calendar',
        'com_dotnet',
        'Core',
        'ctype',
        'curl',
        'date',
        'dba',
        'dom',
        'enchant',
        'exif',
        'FFI',
        'fileinfo',
        'filter',
        'fpm',
        'ftp',
        'gd',
        'gettext',
        'gmp',
        'hash',
        'iconv',
        'imap',
        'intl',
        'json',
        'ldap',
        'libxml',
        'mbstring',
        'meta',
        'mysqli',
        'oci8',
        'odbc',
        'openssl',
        'pcntl',
        'pcre',
        'PDO',
        'pdo_ibm',
        'pdo_mysql',
        'pdo_pgsql',
        'pdo_sqlite',
        'pgsql',
        'Phar',
        'posix',
        'pspell',
        'readline',
        'Reflection',
        'session',
        'shmop',
        'SimpleXML',
        'snmp',
        'soap',
        'sockets',
        'sodium',
        'SPL',
        'sqlite3',
        'standard',
        'superglobals',
        'sysvmsg',
        'sysvsem',
        'sysvshm',
        'tidy',
        'tokenizer',
        'xml',
        'xmlreader',
        'xmlrpc',
        'xmlwriter',
        'xsl',
        'Zend OPcache',
        'zip',
        'zlib',
        -- not default
        'imagick',
      },
    },
  },
}
