#!/bin/bash

case $BLOCK_BUTTON in
1) pavucontrol ;;
esac

VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')

if [[ "$RAW" == *"[MUTED]"* ]]; then
    ICON="󰝟"
    COLOR="#181825"
else
    if [ "$VOL" -ge 70 ]; then
        ICON="󰕾"
        COLOR="#a6e3a1"
    elif [ "$VOL" -ge 30 ]; then
        ICON="󰖀"
        COLOR="#f9e2af"
    elif [ "$VOL" -gt 0 ]; then
        ICON="󰕿"
        COLOR="#cdd6f4"
    else
        ICON="󰝟"
        COLOR="#bac2de"
    fi
fi

echo "<span color='$COLOR'>$ICON</span>"
